[package]
name = "my-project"
version = "0.1.0"
edition = "2024"

[dependencies]
lezard = { path = ".." }
log = "0.4.28"
env_logger = "0.10"
anyhow = "1.0.98"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros"] }
